baseURL = "/"
languageCode = "en-us"
#title = "PsiCode"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Portfolio"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "History"
    URL = "history"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/psi4square_digit4_overdark_pink.png"
logo_width = 300
favicon = "images/favicon-psi4.ico"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "PsiCode"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css", "css/dltable.css"]
psi4_html = """<span style="font-family: Optima, sans-serif;font-weight: normal;">P<span style="font-size: 82%;">SI</span>4</span>"""

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/wikipedia-buckycatcher.jpg"
    #heading = "Psi4"
    content= "Open-Source Quantum Chemistry"
    btn = true
    btnText="Compute"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Great Design & Incredible Features"
    content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
    btnURL = "#"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "320"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "565"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        faicon = "fa-home"
        url = "http://psicode.org/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        faicon = "fa-twitter"
        url = "https://twitter.com/PSI_Code"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        faicon = "fa-comments"
        url = "http://forum.psicode.org"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        faicon = "fa-youtube"
        url = "https://www.youtube.com/user/psitutorials"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        faicon = "fa-github"
        url = "https://github.com/psi4/psi4/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        faicon = "fa-slack-hash"
        url = "https://join.slack.com/t/psi4/shared_invite/enQtNDUyOTYzNTE0NjQ3LWExZDhkY2U4MTM1ZDZlNTBkNjMyMDcxZmFkN2NmYmZkMzliNzY2ZDc2OTBlYTk5ZTA2OGRkNWYxNzJmN2QyYWM"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
